import { Guide, Spot } from '@/types'

function buildDayPlans(spots: Spot[], days: number) {
  const sorted = [...spots].sort((a, b) => {
    const order: Record<string, number> = { '上午': 0, '中午': 1, '下午': 2, '晚上': 3 }
    return (order[a.timeSlot] ?? 0) - (order[b.timeSlot] ?? 0)
  })
  const spotsPerDay = Math.ceil(sorted.length / days)
  return Array.from({ length: days }, (_, i) => ({
    day: i + 1,
    title: `第${i + 1}天`,
    spots: sorted.slice(i * spotsPerDay, (i + 1) * spotsPerDay),
    budgetEstimate: i === 0 ? '约150-280元' : '约100-200元',
  }))
}

const nanjingSpots: Spot[] = [
  {
    id: 'nj-1', name: '夫子庙秦淮河畔', desc: '桨声灯影，六朝金粉地的夜色',
    duration: '2.5小时', tags: ['文化', '体验'], timeSlot: '晚上',
    location: { lat: 32.0210, lng: 118.7890 }, address: '南京市秦淮区贡院街',
    story: '秦淮河是南京的母亲河，夫子庙一带自六朝便是繁华之地。朱自清写下名篇《桨声灯影里的秦淮河》，写尽了灯影里的朦胧与历史的回响。',
    type: '体验', budgetHint: '免费逛街', goodNow: true, goodNowReason: '华灯初上最有意境', photoSpot: true, emoji: '🏮',
    originalText: '我们默默地坐着，看江里帆影的流动，看河心洲上五色的灯光。',
    originalSource: '朱自清《桨声灯影里的秦淮河》',
    realityNote: '建议傍晚从文德桥步行至白鹭洲，乘画舫夜游。鸭血粉丝汤认准回味、小潘记等老店。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 朱自清散文名篇——桨声灯影里的秦淮河',
  },
  {
    id: 'nj-2', name: '鸡鸣寺', desc: '南朝四百八十寺，樱花季满城皆粉',
    duration: '1.5小时', tags: ['文化', '自然'], timeSlot: '上午',
    location: { lat: 32.0610, lng: 118.7950 }, address: '南京市玄武区鸡鸣寺路1号',
    story: '鸡鸣寺始建于南朝，是南京最古老的佛寺之一。春季樱花大道是南京最具仪式感的赏花地。',
    type: '景点', budgetHint: '门票10元', photoSpot: true, emoji: '🌸',
    originalText: '千里莺啼绿映红，水村山郭酒旗风。南朝四百八十寺，多少楼台烟雨中。',
    originalSource: '杜牧《江南春》',
    realityNote: '从北门出可登明城墙俯瞰玄武湖。樱花季3-4月需提前预约。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 杜牧"南朝四百八十寺，多少楼台烟雨中"',
  },
  {
    id: 'nj-3', name: '玄武湖', desc: '六朝烟水，城中最大湖泊',
    duration: '2小时', tags: ['自然', '文化'], timeSlot: '下午',
    location: { lat: 32.0700, lng: 118.7950 }, address: '南京市玄武区玄武巷1号',
    story: '玄武湖距今已有2200多年历史，与紫金山、明城墙构成南京城中轴线的生态核心。',
    type: '景点', budgetHint: '免费', goodNow: true, goodNowReason: '下午环湖骑行最佳', emoji: '🌊',
    originalText: '春花秋月何时了，往事知多少。',
    originalSource: '李煜《虞美人》',
    realityNote: '建议租自行车环湖，樱洲春季花开，梁洲适合看日落。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 李煜"春花秋月何时了"',
  },
  {
    id: 'nj-4', name: '老门东', desc: '明清老街巷，城南烟火气',
    duration: '2小时', tags: ['文化', '美食'], timeSlot: '下午',
    location: { lat: 32.0120, lng: 118.7840 }, address: '南京市秦淮区箍桶巷',
    story: '老门东是南京城南传统民居聚集地，比夫子庙更生活化，藏着糖芋苗、赤豆元宵等金陵小吃。',
    type: '体验', budgetHint: '自由消费', photoSpot: true, emoji: '🏘️',
    originalText: '烟水寒，枫林老，草枯霜白，月明风清，正是游赏好时节。',
    originalSource: '《金陵景物志》',
    realityNote: '推荐蓝老大糖芋苗、蒋有记牛肉锅贴，比夫子庙人少价实。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 影视剧取景地——明清老街巷老门东',
  },
  {
    id: 'nj-5', name: '鸭血粉丝汤', desc: '金陵第一小吃，鸭血嫩滑粉丝鲜',
    duration: '45分钟', tags: ['美食'], timeSlot: '中午',
    location: { lat: 32.0400, lng: 118.7800 }, address: '南京市秦淮区多家老店',
    story: '鸭血粉丝汤以老鸭汤为底，配鸭血、鸭肠、鸭肝和粉丝，是南京城市味觉名片。',
    type: '美食', budgetHint: '人均15-25元', goodNow: true, goodNowReason: '午餐或夜宵皆宜', emoji: '🍜',
    originalText: '金陵自古繁华地，美食甲于东南。',
    originalSource: '《金陵岁时记》',
    realityNote: '回味鸭血粉丝汤、小潘记为连锁老店，加辣油香菜，汤要喝完。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 金陵美食文化——鸭血粉丝汤',
  },
]

const suzhouSpots: Spot[] = [
  {
    id: 'sz-1', name: '拙政园', desc: '中国四大名园之首，咫尺之内再造乾坤',
    duration: '2.5小时', tags: ['文化'], timeSlot: '上午',
    location: { lat: 31.3250, lng: 120.6310 }, address: '苏州市姑苏区东北街178号',
    story: '拙政园始建于明代，沈复《浮生六记》中描写的苏州园林意境正与此园一脉相承。',
    type: '景点', budgetHint: '门票80元', photoSpot: true, emoji: '🏯',
    originalText: '园林之美，在于疏密有致，虚实相生。此间一步一景，正如画理。',
    originalSource: '沈复《浮生六记》',
    realityNote: '建议7:30开园即入。从东花园经中园到西园，西部盆景园人少景幽。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈复《浮生六记》中的苏州园林意境',
  },
  {
    id: 'sz-2', name: '平江路', desc: '姑苏水巷，枕河人家',
    duration: '2小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 31.3180, lng: 120.6370 }, address: '苏州市姑苏区平江路',
    story: '平江路是苏州古城保存最完整的历史街区，河畔评弹声、摇橹船、苏式糕点铺，是活着的江南。',
    type: '体验', budgetHint: '自由消费', goodNow: true, goodNowReason: '傍晚水巷灯光最美', photoSpot: true, emoji: '🛶',
    originalText: '姑苏城外寒山寺，夜半钟声到客船。',
    originalSource: '张继《枫桥夜泊》',
    realityNote: '从拙政园步行10分钟可达，推荐听一曲评弹，尝松鹤楼枣泥拉糕。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 张继"姑苏城外寒山寺，夜半钟声到客船"',
  },
  {
    id: 'sz-3', name: '虎丘', desc: '吴中第一名胜，斜塔千年不倒',
    duration: '2小时', tags: ['文化', '历史'], timeSlot: '上午',
    location: { lat: 31.3340, lng: 120.5800 }, address: '苏州市姑苏区虎丘山门内8号',
    story: '苏轼说「到苏州不游虎丘，乃憾事也」，云岩寺塔俗称东方比萨斜塔。',
    type: '景点', budgetHint: '门票70元', emoji: '🗼',
    originalText: '到苏州而不游虎丘，乃憾事也。',
    originalSource: '苏轼语',
    realityNote: '从山门沿剑池上行至斜塔，春季杜鹃花展值得一看。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 苏轼"到苏州不游虎丘，乃憾事也"',
  },
  {
    id: 'sz-4', name: '寒山寺', desc: '夜半钟声，客船听枫桥',
    duration: '1.5小时', tags: ['文化'], timeSlot: '下午',
    location: { lat: 31.3100, lng: 120.5680 }, address: '苏州市姑苏区寒山寺弄24号',
    story: '寒山寺因张继《枫桥夜泊》闻名天下，每年除夕敲钟108响是江南最盛大的跨年仪式之一。',
    type: '景点', budgetHint: '门票20元', emoji: '🔔',
    originalText: '姑苏城外寒山寺，夜半钟声到客船。',
    originalSource: '张继《枫桥夜泊》',
    realityNote: '可步行过枫桥，碑廊存有历代《枫桥夜泊》石刻。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 张继《枫桥夜泊》——寒山寺夜半钟声',
  },
  {
    id: 'sz-5', name: '苏帮菜', desc: '松鼠桂鱼、响油鳝糊，甜鲜为本',
    duration: '1.5小时', tags: ['美食'], timeSlot: '晚上',
    location: { lat: 31.3000, lng: 120.6200 }, address: '苏州市观前街一带',
    story: '苏帮菜以甜鲜细腻著称，松鼠桂鱼刀工如画，响油鳝糊上桌犹嘶嘶作响。',
    type: '美食', budgetHint: '人均80-150元', emoji: '🐟',
    originalText: '饮食之道，清鲜和润，乃吴中之正味。',
    originalSource: '《苏州府志·风俗》',
    realityNote: '观前街得月楼、松鹤楼为百年老店，松鼠桂鱼偏甜宜配碧螺虾仁。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 苏州饮食文化——吴中正味',
  },
]

const wuxiSpots: Spot[] = [
  {
    id: 'wx-1', name: '鼋头渚', desc: '太湖第一名胜，樱花三万余株',
    duration: '3小时', tags: ['自然', '文化'], timeSlot: '上午',
    location: { lat: 31.5200, lng: 120.2180 }, address: '无锡市滨湖区鼋渚路1号',
    story: '郭沫若题「太湖佳绝处，毕竟在鼋头」，三月樱花谷万株齐放是长三角最壮观赏樱地之一。',
    type: '景点', budgetHint: '门票90元', photoSpot: true, emoji: '🌸',
    originalText: '太湖佳绝处，毕竟在鼋头。',
    originalSource: '郭沫若题鼋头渚',
    realityNote: '樱花季建议工作日早7点入园，非花季可登太湖仙岛。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 郭沫若"太湖佳绝处，毕竟在鼋头"',
  },
  {
    id: 'wx-2', name: '惠山古镇', desc: '寄畅园畔，泥人茶香',
    duration: '2小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 31.5890, lng: 120.2780 }, address: '无锡市梁溪区惠山直街',
    story: '惠山泥人、二泉映月、天下第二泉皆在此，寄畅园为江南名园，乾隆六下江南五次驻跸。',
    type: '景点', budgetHint: '古镇免费，寄畅园70元', emoji: '🍵',
    originalText: '二泉映月，惠山泥人，江南风物尽在眼前。',
    originalSource: '《惠山记》',
    realityNote: '二泉亭品泉茶，惠山泥人博物馆可体验捏塑。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 二泉映月·惠山泥人——江南风物',
  },
  {
    id: 'wx-3', name: '无锡小笼', desc: '皮薄汁多，先开窗后喝汤',
    duration: '1小时', tags: ['美食'], timeSlot: '中午',
    location: { lat: 31.5700, lng: 120.3000 }, address: '无锡市南禅寺附近',
    story: '无锡小笼以皮薄馅大汁多著称，王兴记、熙盛源为本地人常去老店。',
    type: '美食', budgetHint: '人均30-50元', goodNow: true, goodNowReason: '早午餐皆宜', emoji: '🥟',
    originalText: '江南点心，以无锡小笼为绝，鲜而不腻。',
    originalSource: '《无锡县志·食货》',
    realityNote: '熙盛源鲜肉小笼配姜丝醋，轻提慢移避免烫口。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 无锡饮食文化——江南点心之绝',
  },
  {
    id: 'wx-4', name: '南长街', desc: '运河古街，灯火映水',
    duration: '2小时', tags: ['文化', '体验'], timeSlot: '晚上',
    location: { lat: 31.5630, lng: 120.3120 }, address: '无锡市梁溪区南长街',
    story: '南长街沿古运河而建，运河夜游、泥塑馆、茶馆散布其间，夜景比白日更有韵味。',
    type: '体验', budgetHint: '自由消费', goodNow: true, goodNowReason: '夜景最佳', photoSpot: true, emoji: '🌃',
    originalText: '运河千里，无锡最繁华处在此。',
    originalSource: '《运河志》',
    realityNote: '从清明桥步行至南禅寺，晚间可乘运河游船。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 大运河文化——无锡南长街',
  },
]

const zhenjiangSpots: Spot[] = [
  {
    id: 'zj-1', name: '金山寺', desc: '白娘子水漫金山，江天禅寺',
    duration: '2小时', tags: ['文化', '历史'], timeSlot: '上午',
    location: { lat: 32.2210, lng: 119.4030 }, address: '镇江市润州区金山路62号',
    story: '金山寺始建于东晋，传说《白蛇传》中白娘子水漫金山即发生于此。',
    type: '景点', budgetHint: '门票65元', photoSpot: true, emoji: '⛩️',
    originalText: '山不在高，有仙则名。水不在深，有龙则灵。',
    originalSource: '刘禹锡《陋室铭》',
    realityNote: '登慈寿塔俯瞰长江，文创区有白蛇传说展。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 《白蛇传》"水漫金山"传说发生地',
  },
  {
    id: 'zj-2', name: '焦山', desc: '书法摩崖，长江第一江防',
    duration: '2小时', tags: ['文化', '自然'], timeSlot: '下午',
    location: { lat: 32.2280, lng: 119.4500 }, address: '镇江市润州区东吴路83号',
    story: '焦山以《瘗鹤铭》摩崖石刻闻名，被誉为「大字之祖」，定慧寺香火鼎盛。',
    type: '景点', budgetHint: '门票50元', emoji: '🖋️',
    originalText: '大江奔流，焦山独立，书法石刻，千古绝唱。',
    originalSource: '《焦山志》',
    realityNote: '需乘渡船登岛，万佛塔可远眺长江大桥。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 焦山《瘗鹤铭》——大字之祖',
  },
  {
    id: 'zj-3', name: '西津渡', desc: '千年古渡，三国遗风',
    duration: '1.5小时', tags: ['文化'], timeSlot: '下午',
    location: { lat: 32.2130, lng: 119.4320 }, address: '镇江市润州区西津渡街',
    story: '西津渡是镇江最古老的渡口，石板街、昭关石塔、英国领事馆旧址叠压千年码头史。',
    type: '体验', budgetHint: '免费', photoSpot: true, emoji: '🏛️',
    originalText: '京口瓜洲一水间，钟山只隔数重山。',
    originalSource: '王安石《泊船瓜洲》',
    realityNote: '傍晚前往最佳，附近锅盖面老店集中。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 王安石"京口瓜洲一水间"',
  },
  {
    id: 'zj-4', name: '镇江锅盖面', desc: '面锅煮面，锅盖浮汤',
    duration: '45分钟', tags: ['美食'], timeSlot: '中午',
    location: { lat: 32.2100, lng: 119.4300 }, address: '镇江市润州区多家面馆',
    story: '锅盖面是镇江独有吃法，配肴肉、香醋，是镇江人早餐的灵魂。',
    type: '美食', budgetHint: '人均15-20元', goodNow: true, goodNowReason: '早餐首选', emoji: '🍜',
    originalText: '面要锅盖，肴要香醋，镇江一绝。',
    originalSource: '镇江民间食谚',
    realityNote: '大华面馆、邵顺兴为本地名店，点长鱼面或腰花面。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 镇江饮食文化——锅盖面与肴肉',
  },
]

const now = new Date().toISOString()

export const cityGuides: Record<string, Guide> = {
  nanjing: {
    id: 'nanjing',
    title: '桨声灯影里的南京',
    subtitle: '跟着朱自清，夜游秦淮河畔',
    city: '南京',
    province: '江苏',
    days: 2,
    interests: ['文化', '美食', '自然'],
    budget: '舒适',
    dayPlans: buildDayPlans(nanjingSpots, 2),
    dialect: [
      { dialect: '阿要', meaning: '要不要', scenario: '阿要吃鸭血粉丝' },
      { dialect: '蛮好', meaning: '很好', scenario: '评价事物' },
      { dialect: '乖乖', meaning: '天哪', scenario: '表示惊讶' },
      { dialect: '韶', meaning: '漂亮', scenario: '形容好看' },
      { dialect: '老杆子', meaning: '老江湖', scenario: '形容老练' },
    ],
    localExperiences: [
      { name: '秦淮画舫夜游', desc: '桨声灯影里的秦淮河', type: '民俗', schedule: '每日晚间' },
      { name: '鸡鸣寺樱花季', desc: '城墙下樱花大道', type: '时令', schedule: '3-4月' },
      { name: '玄武湖环湖骑行', desc: '六朝烟水画中游', type: '体验', schedule: '全天' },
    ],
    createdAt: now,
    tips: ['夫子庙夜游建议工作日去', '鸭血粉丝认准回味、小潘记', '鸡鸣寺樱花季需预约', '老门东比夫子庙更生活化'],
    entryType: '目的地',
    relatedBook: '《桨声灯影里的秦淮河》',
    relatedAuthor: '朱自清',
    routeIntro: '六朝金粉地，金陵帝王州。朱自清笔下「桨声灯影里的秦淮河」，写尽了南京的夜色与历史。从夫子庙秦淮河畔出发，登鸡鸣寺、环玄武湖、逛老门东——一座城市的文学与烟火，都在这里。',
  },
  suzhou: {
    id: 'suzhou',
    title: '姑苏城外有浮生',
    subtitle: '跟着沈复与张继，走进江南园林',
    city: '苏州',
    province: '江苏',
    days: 2,
    interests: ['文化', '美食', '体验'],
    budget: '舒适',
    dayPlans: buildDayPlans(suzhouSpots, 2),
    dialect: [
      { dialect: '阿要', meaning: '要不要', scenario: '阿要吃糕' },
      { dialect: '蛮好', meaning: '很好', scenario: '蛮好个园林' },
      { dialect: '辰光', meaning: '时候', scenario: '啥辰光去' },
      { dialect: '勿要', meaning: '不要', scenario: '勿要客气' },
      { dialect: '结棍', meaning: '厉害', scenario: '园林造得结棍' },
    ],
    localExperiences: [
      { name: '平江路评弹', desc: '水巷深处听吴侬软语', type: '民俗', schedule: '每日' },
      { name: '拙政园晨游', desc: '开园即入避开人流', type: '体验', schedule: '7:30' },
      { name: '寒山寺除夕敲钟', desc: '夜半钟声到客船', type: '民俗', schedule: '除夕' },
    ],
    createdAt: now,
    tips: ['拙政园务必早去', '平江路傍晚最美', '苏帮菜偏甜提前有心理准备', '虎丘与寒山寺可安排同日'],
    entryType: '目的地',
    relatedBook: '《浮生六记》',
    relatedAuthor: '沈复 / 张继',
    routeIntro: '「姑苏城外寒山寺，夜半钟声到客船。」张继一首七绝，让苏州成为中国人心中的江南。拙政园、平江路、虎丘、寒山寺——跟着诗文走，才是读懂苏州的方式。',
  },
  wuxi: {
    id: 'wuxi',
    title: '太湖佳绝在鼋头',
    subtitle: '樱花、泥人、小笼，江南另一种温润',
    city: '无锡',
    province: '江苏',
    days: 1,
    interests: ['自然', '美食', '文化'],
    budget: '舒适',
    dayPlans: buildDayPlans(wuxiSpots, 1),
    dialect: [
      { dialect: '阿要', meaning: '要不要', scenario: '阿要吃小笼' },
      { dialect: '蛮好', meaning: '很好', scenario: '评价风景' },
      { dialect: '老灵', meaning: '很好', scenario: '形容棒' },
      { dialect: '勿要', meaning: '不要', scenario: '勿要催' },
      { dialect: '扎劲', meaning: '厉害', scenario: '樱花扎劲好看' },
    ],
    localExperiences: [
      { name: '鼋头渚樱花季', desc: '三万株樱花齐放', type: '时令', schedule: '3-4月' },
      { name: '惠山泥人体验', desc: '亲手捏一只大阿福', type: '手艺', schedule: '周末' },
      { name: '古运河夜游', desc: '南长街灯火映水', type: '民俗', schedule: '晚间' },
    ],
    createdAt: now,
    tips: ['樱花季鼋头渚务必早起', '小笼推荐熙盛源、王兴记', '惠山古镇与南长街可连游', '太湖游船视天气而定'],
    entryType: '目的地',
    relatedBook: '《太湖志》',
    relatedAuthor: '郭沫若',
    routeIntro: '「太湖佳绝处，毕竟在鼋头」。无锡有太湖的浩渺、惠山的泥人与茶、以及让人惦记一整年的小笼包。一日漫游，足以体会江南的另一种温润。',
  },
  zhenjiang: {
    id: 'zhenjiang',
    title: '三山镇江',
    subtitle: '金山焦山，锅盖面与长江风',
    city: '镇江',
    province: '江苏',
    days: 1,
    interests: ['文化', '美食', '体验'],
    budget: '舒适',
    dayPlans: buildDayPlans(zhenjiangSpots, 1),
    dialect: [
      { dialect: '阿要', meaning: '要不要', scenario: '阿要吃面' },
      { dialect: '蛮好', meaning: '很好', scenario: '评价' },
      { dialect: '老', meaning: '很', scenario: '老好吃' },
      { dialect: '来斯', meaning: '漂亮', scenario: '风景来斯' },
      { dialect: '扎劲', meaning: '厉害', scenario: '面扎劲' },
    ],
    localExperiences: [
      { name: '金山寺白蛇传说', desc: '水漫金山的故事发生地', type: '民俗', schedule: '全天' },
      { name: '焦山碑林拓片', desc: '书法爱好者必访', type: '手艺', schedule: '周末' },
      { name: '西津渡古渡步行', desc: '千年码头石板街', type: '体验', schedule: '傍晚' },
    ],
    createdAt: now,
    tips: ['金山焦山各需半天', '锅盖面早餐吃最地道', '西津渡傍晚拍照最佳', '配镇江香醋和肴肉'],
    entryType: '目的地',
    relatedBook: '《白蛇传》',
    relatedAuthor: '民间传说 / 王安石',
    routeIntro: '王安石「京口瓜洲一水间」，写的就是镇江与扬州隔江相望。金山寺、焦山、西津渡，再加一碗锅盖面——这座长江边的城市，有传奇、有书法、有烟火气。',
  },
}
