import { Guide, Spot } from '@/types'

function buildDayPlans(spots: Spot[], days: number) {
  const sorted = [...spots].sort((a, b) => {
    const order: Record<string, number> = { '上午': 0, '中午': 1, '下午': 2, '晚上': 3 }
    return (order[a.timeSlot] ?? 0) - (order[b.timeSlot] ?? 0)
  })
  const spotsPerDay = Math.ceil(sorted.length / days)
  return Array.from({ length: days }, (_, i) => ({
    day: i + 1,
    title: `第${i + 1}天`,
    spots: sorted.slice(i * spotsPerDay, (i + 1) * spotsPerDay),
    budgetEstimate: i === 0 ? '约150-280元' : '约100-200元',
  }))
}

// ============================================================
//  凤凰（湘西）— 📖《边城》沈从文
// ============================================================
const fenghuangSpots: Spot[] = [
  {
    id: 'fh-1', name: '沈从文故居', desc: '文学巨匠的出生地，百年清代四合院',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 27.9487, lng: 109.5990 }, address: '湖南省湘西凤凰县沱江镇中营街21号',
    story: '文学巨匠沈从文的出生地，百年清代四合院内保留先生手稿与旧物，是读懂《边城》的必访人文点位。',
    type: '景点', budgetHint: '单票40元/九景联票128元', emoji: '🏠',
    originalText: '翠翠坐在溪边，望着溪面为暮色所笼罩的一切，且望到那只渡船上一群过渡人',
    originalSource: '📖沈从文《边城》',
    realityNote: '故居为典型湘西四合院，内陈列沈从文手稿、书信与生活旧物，值得细细品读。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈从文《边城》——作者出生地与故居',
  },
  {
    id: 'fh-2', name: '沱江泛舟', desc: '乌篷船顺流而下，两岸吊脚楼如画卷',
    duration: '1.5小时', tags: ['体验', '文化'], timeSlot: '上午',
    location: { lat: 27.9515, lng: 109.5995 }, address: '凤凰古城北门码头',
    story: '乘乌篷船顺流而下，两岸吊脚楼如画卷展开，船夫哼唱苗族山歌，仿佛驶入《边城》的水墨世界。',
    type: '体验', budgetHint: '日游85元/夜游80元', goodNow: true, goodNowReason: '清晨薄雾中泛舟最美', photoSpot: true, emoji: '🛶',
    originalText: '茶峒地方凭水依山筑城……贯串各个码头有一条河街，人家房子多一半着陆，一半在水，因为余地有限，那些房子莫不设有吊脚楼。',
    originalSource: '📖沈从文《边城》第二章',
    realityNote: '建议清晨乘坐，薄雾贴水，吊脚楼若隐若现。夜游19:00后开始，灯光映水别有韵味。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈从文《边城》——沱江吊脚楼水上世界',
  },
  {
    id: 'fh-3', name: '虹桥风雨楼', desc: '明代风雨桥，俯瞰沱江S弯最佳上帝视角',
    duration: '1小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 27.9495, lng: 109.5985 }, address: '湖南省湘西凤凰县沱江镇虹桥中路',
    story: '始建于明代的标志性风雨桥，三层阁楼式建筑，二楼是俯瞰沱江S弯的最佳上帝视角。',
    type: '景点', budgetHint: '免费（登楼含九景联票内）', photoSpot: true, emoji: '🌉',
    originalText: '落日向上游翠翠家中的那一方落去，黄昏把河面装饰了一层银色薄雾。',
    originalSource: '📖沈从文《边城》',
    realityNote: '二楼观景台是凤凰最佳拍摄点，建议黄昏时分前往，落日薄雾如诗如画。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈从文《边城》——虹桥风雨楼观沱江',
  },
  {
    id: 'fh-4', name: '沱江跳岩', desc: '红砂岩墩古渡口，凤凰最具画意的瞬间',
    duration: '30分钟', tags: ['体验', '文化'], timeSlot: '上午',
    location: { lat: 27.9520, lng: 109.5998 }, address: '凤凰古城北门沱江河段',
    story: '两排红砂岩墩组成的古渡口，清晨薄雾中站于石墩之上，吊脚楼倒映水中，是凤凰最具画意的瞬间。',
    type: '体验', budgetHint: '免费', goodNow: true, goodNowReason: '清晨薄雾中最美', photoSpot: true, emoji: '🪨',
    originalText: '河面已朦朦胧胧，看上去好像一只白鸭在潭中浮着……',
    originalSource: '📖沈从文《边城》',
    realityNote: '跳岩石面湿滑，拍照务必站稳扶好。清晨人少雾气重，最出片。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈从文《边城》——沱江跳岩古渡口',
  },
  {
    id: 'fh-5', name: '万名塔', desc: '七层古塔矗立沱江边，凤凰最经典夜景',
    duration: '30分钟', tags: ['文化'], timeSlot: '晚上',
    location: { lat: 27.9470, lng: 109.5990 }, address: '凤凰古城沱江沙湾段',
    story: '七层古塔矗立沱江边，夜间灯火辉映水面倒影，与吊脚楼构成凤凰最经典的夜景画面。',
    type: '景点', budgetHint: '免费', photoSpot: true, emoji: '🗼',
    originalText: '黄昏来时，翠翠坐在家中屋后白塔下，看天空为夕阳烘成桃红色的薄云……',
    originalSource: '📖沈从文《边城》',
    realityNote: '夜景19:00准时亮灯，万名塔灯光映水面，是凤凰最经典的夜景拍摄点。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈从文《边城》——万名塔与白塔意境',
  },
  {
    id: 'fh-6', name: '南华山', desc: '登临山顶360°俯瞰古城与沱江全貌',
    duration: '2小时', tags: ['自然', '文化'], timeSlot: '下午',
    location: { lat: 27.9450, lng: 109.5980 }, address: '凤凰古城南侧',
    story: '登临山顶可360°俯瞰古城全景与沱江全貌，是凤凰最壮阔的观景台。',
    type: '景点', budgetHint: '神凤文化景区待确认', emoji: '⛰️',
    originalText: '白日渐长，不知什么时节，守在船头的祖父睡着了，躺在岸上的翠翠同黄狗也睡着了。',
    originalSource: '📖沈从文《边城》',
    realityNote: '登山步道约30分钟，山顶观景台可览古城全貌，傍晚看日落最佳。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈从文《边城》——南华山俯瞰边城全景',
  },
  {
    id: 'fh-7', name: '血粑鸭', desc: '凤凰招牌菜，鸭血糯米饼配鸭肉香糯入味',
    duration: '1小时', tags: ['美食'], timeSlot: '中午',
    location: { lat: 27.9500, lng: 109.5990 }, address: '大使饭店（古城内）',
    story: '血粑鸭是凤凰最具代表性的菜肴，鸭血与糯米做成血粑，和鸭肉一起炖煮，香糯入味，是来凤凰必尝的味道。',
    type: '美食', budgetHint: '68元/份', goodNow: true, goodNowReason: '午餐必点', emoji: '🍗',
    originalText: '三天不吃酸，走路打捞蹿。',
    originalSource: '湘西饮食俗语',
    realityNote: '大使饭店的血粑鸭口碑最佳，68元/份，建议两人分享。古城内各餐馆也有供应。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 湘西饮食文化——凤凰血粑鸭',
  },
  {
    id: 'fh-8', name: '东门城楼', desc: '清康熙古城门，凤凰防御体系见证',
    duration: '45分钟', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 27.9505, lng: 109.6010 }, address: '凤凰古城东门',
    story: '清康熙年间建造的古城门楼，与北门城楼同为凤凰古城防御体系的见证，城楼巍峨，古风犹存。',
    type: '景点', budgetHint: '含九景联票128元内', emoji: '🏯',
    originalText: '近山的一面，城墙俨然如一条长蛇，缘山爬去',
    originalSource: '📖沈从文《边城》第二章',
    realityNote: '城楼可登，俯瞰古城街巷。与沈从文故居、熊希龄故居可连游。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 沈从文《边城》——东门城楼与古城墙',
  },
]

// ============================================================
//  上海 — 🎬《繁花》·📖张爱玲·📖鲁迅
// ============================================================
const shanghaiSpots: Spot[] = [
  {
    id: 'sh-1', name: '和平饭店', desc: '外滩地标，爷叔与宝总的长期包房所在地',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 31.2423, lng: 121.4903 }, address: '上海市黄浦区南京东路20号',
    story: '外滩地标，剧中爷叔与宝总的长期包房所在地，远东第一酒店的百年传奇。',
    type: '景点', budgetHint: '免费参观一楼', photoSpot: true, emoji: '🏨',
    originalText: '做生意要先学会两个字，不响。',
    originalSource: '🎬《繁花》（电视剧版，胡歌饰阿宝台词）',
    realityNote: '一楼大厅免费参观，繁花同款套餐另计。建议上午前往，人少光线好。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 电视剧《繁花》——爷叔与宝总包房地和平饭店',
  },
  {
    id: 'sh-2', name: '黄河路', desc: '90年代上海"美食一条街"，至真园原型所在',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 31.2405, lng: 121.4748 }, address: '上海市黄浦区黄河路',
    story: '90年代上海"美食一条街"，剧中至真园（苔圣园）、金美林等酒楼所在地，繁华的象征。',
    type: '体验', budgetHint: '免费', goodNow: true, goodNowReason: '下午漫步最有感觉', photoSpot: true, emoji: '🏮',
    originalText: '电灯下面数钞票，数清一沓，放进西装内袋，再数一沓……这半分钟，是上海味道。',
    originalSource: '📖金宇澄《繁花》开篇',
    realityNote: '真正的黄河路在市区免费参观，《繁花》实景在车墩影视乐园（门票80元）。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 电视剧《繁花》——至真园原型黄河路',
  },
  {
    id: 'sh-3', name: '进贤路', desc: '"夜东京"所在路，市井弄堂与潮流小店',
    duration: '1小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 31.2308, lng: 121.4708 }, address: '上海市黄浦区进贤路',
    story: '剧中玲子经营的"夜东京"所在路，短短几百米浓缩了上海的市井弄堂生活与潮流小店。',
    type: '体验', budgetHint: '免费', goodNow: true, goodNowReason: '弄堂里散步很惬意', emoji: '🏘️',
    originalText: '阿宝说，乖小囡，记性真好',
    originalSource: '📖金宇澄《繁花》',
    realityNote: '进贤路不长，可从茂名南路走到长乐路，沿途有老式里弄和小资咖啡馆。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 电视剧《繁花》——夜东京所在进贤路',
  },
  {
    id: 'sh-4', name: '国际饭店', desc: '"远东第一高楼"，蝴蝶酥上海网红美食',
    duration: '1小时', tags: ['文化', '美食'], timeSlot: '上午',
    location: { lat: 31.2365, lng: 121.4735 }, address: '上海市黄浦区南京西路170号',
    story: '1934年建成的"远东第一高楼"，剧中宝总从阳台眺望黄河路繁华，其蝴蝶酥是上海网红美食。',
    type: '景点', budgetHint: '免费参观大堂', emoji: '🏢',
    originalText: '派头——做生意在上海要有三头：派头、噱头、苗头',
    originalSource: '🎬《繁花》（爷叔教导阿宝）',
    realityNote: '西饼屋08:00-23:30，蝴蝶酥常年排队，建议早上8点前往。大堂免费参观。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 电视剧《繁花》——宝总眺望黄河路的国际饭店',
  },
  {
    id: 'sh-5', name: '常德公寓', desc: '张爱玲故居，写出《倾城之恋》等名作',
    duration: '30分钟', tags: ['文化'], timeSlot: '下午',
    location: { lat: 31.2275, lng: 121.4485 }, address: '上海市静安区常德路195号',
    story: '张爱玲在此居住约五年，写出《倾城之恋》《金锁记》《红玫瑰与白玫瑰》等名作，旧称"爱丁顿公寓"。',
    type: '景点', budgetHint: '免费（仅可外观）', photoSpot: true, emoji: '🏢',
    originalText: '在这个光怪陆离的人间，没有谁可以将日子过得行云流水。',
    originalSource: '📖张爱玲散文',
    realityNote: '仍为居民住宅，不对外开放，仅可外观拍照，请勿扰民。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 张爱玲故居——写出《倾城之恋》的爱丁顿公寓',
  },
  {
    id: 'sh-6', name: '上海鲁迅故居', desc: '鲁迅上海最后寓所，写下《且介亭杂文》',
    duration: '1小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 31.2685, lng: 121.4765 }, address: '上海市虹口区山阴路132弄9号',
    story: '鲁迅先生在上海最后的寓所，写下《且介亭杂文》等作品，不足十平米的"老虎尾巴"书房诞生了《野草》与《彷徨》。',
    type: '景点', budgetHint: '待确认', emoji: '📖',
    originalText: '其实地上本没有路，走的人多了，也便成了路。',
    originalSource: '📖鲁迅《故乡》',
    realityNote: '9:00-16:00开放，免预约现场购票。与鲁迅纪念馆、鲁迅墓可连游。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 鲁迅故居——"老虎尾巴"书房与《野草》',
  },
  {
    id: 'sh-7', name: '排骨年糕', desc: '《繁花》带火，外卖量暴涨200%的上海味道',
    duration: '45分钟', tags: ['美食'], timeSlot: '中午',
    location: { lat: 31.2350, lng: 121.4750 }, address: '鲜得来/剧中同款',
    story: '排骨年糕是上海老味道，《繁花》播出后外卖量暴涨200%，鲜得来是老字号代表。',
    type: '美食', budgetHint: '人均25-40元', goodNow: true, goodNowReason: '午餐必点', emoji: '🍖',
    originalText: '不响——不该讲的、讲不清楚的、没想好的、没把握的、为难自己和为难别人的事情都不响。',
    originalSource: '📖金宇澄《繁花》',
    realityNote: '鲜得来排骨年糕是老字号，剧中同款。配一份生煎包，老上海午餐标配。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 电视剧《繁花》带火——排骨年糕上海味道',
  },
  {
    id: 'sh-8', name: '中国证券博物馆', desc: '百年建筑，中国第一盏电灯亮起处',
    duration: '1小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 31.2520, lng: 121.4910 }, address: '上海市虹口区黄浦路15号',
    story: '始建于1846年的百年建筑，中国第一盏电灯在此亮起，上海证券交易所在此开业，《繁花》在此取景。',
    type: '景点', budgetHint: '免费免预约', emoji: '🏛️',
    originalText: '爷叔——上海话中对长辈的尊称，亦师亦父',
    originalSource: '🎬《繁花》',
    realityNote: '周二至周日9:30-16:00开放，免费免预约。繁花取景地之一，可感受上海金融历史。',
    culturalTag: '🎬影视', culturalTagDetail: '🎬 电视剧《繁花》取景地——中国证券博物馆',
  },
]

// ============================================================
//  杭州 — 📖白居易·苏轼·郁达夫
// ============================================================
const hangzhouSpots: Spot[] = [
  {
    id: 'hz-1', name: '白堤', desc: '白居易诗中"绿杨阴里白沙堤"，千年诗情已成湖山',
    duration: '1.5小时', tags: ['文化', '自然'], timeSlot: '上午',
    location: { lat: 30.2575, lng: 120.1520 }, address: '杭州市西湖区白堤（东起断桥，西至平湖秋月）',
    story: '白居易任杭州刺史时修筑（实为白公堤，非此堤），后人以讹传讹将"白沙堤"称为白堤，千年诗情已成湖山一部分。',
    type: '景点', budgetHint: '免费', goodNow: true, goodNowReason: '清晨漫步最美', photoSpot: true, emoji: '🌿',
    originalText: '最爱湖东行不足，绿杨阴里白沙堤。',
    originalSource: '📖白居易《钱塘湖春行》',
    realityNote: '从断桥步行至平湖秋月，约20分钟，晨间人少景幽。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 白居易"最爱湖东行不足，绿杨阴里白沙堤"',
  },
  {
    id: 'hz-2', name: '苏堤', desc: '苏轼疏浚西湖筑堤，"苏堤春晓"西湖十景之首',
    duration: '2小时', tags: ['自然', '文化'], timeSlot: '上午',
    location: { lat: 30.2440, lng: 120.1430 }, address: '杭州市西湖区苏堤（北起栖霞岭，南至南屏山）',
    story: '苏轼第二次任杭州知州时疏浚西湖，以淤泥筑堤，"苏堤春晓"位列西湖十景之首。',
    type: '景点', budgetHint: '免费', goodNow: true, goodNowReason: '清晨苏堤春晓最美', photoSpot: true, emoji: '🌅',
    originalText: '水光潋滟晴方好，山色空蒙雨亦奇。欲把西湖比西子，淡妆浓抹总相宜。',
    originalSource: '📖苏轼《饮湖上初晴后雨》',
    realityNote: '建议租自行车环湖骑行，苏堤白堤串联，省力又惬意。春季桃红柳绿最美。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 苏轼"欲把西湖比西子，淡妆浓抹总相宜"',
  },
  {
    id: 'hz-3', name: '灵隐寺', desc: '白居易入山十二回的"仙灵所隐"之地',
    duration: '2小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 30.2505, lng: 120.1035 }, address: '杭州市西湖区灵隐路法云弄1号',
    story: '东晋咸和元年（326年）始建，白居易入山十二回的"仙灵所隐"之地，千年来文人流连的禅意栖所。',
    type: '景点', budgetHint: '飞来峰45元+灵隐寺30元', emoji: '🛕',
    originalText: '在郡六百日，入山十二回……谁教冷泉水，送我下山来。',
    originalSource: '📖白居易《留题天竺、灵隐两寺》',
    realityNote: '需先购飞来峰门票（45元）再购灵隐寺门票（30元），合计75元。建议早7:00前往避人流。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 白居易"入山十二回"——灵隐寺禅意栖所',
  },
  {
    id: 'hz-4', name: '翁家山', desc: '郁达夫《迟桂花》发生地，桂花比满觉陇晚开',
    duration: '2小时', tags: ['自然', '文化'], timeSlot: '下午',
    location: { lat: 30.2260, lng: 120.1320 }, address: '杭州市西湖区翁家山村（满觉陇西约1公里）',
    story: '海拔稍高，桂花比满觉陇晚开十几天，1932年郁达夫来此成就短篇小说经典《迟桂花》。',
    type: '景点', budgetHint: '免费', goodNow: true, goodNowReason: '秋季赏桂最佳', photoSpot: true, emoji: '🌸',
    originalText: '桂花开的迟，日子也过得慢。',
    originalSource: '📖郁达夫《迟桂花》',
    realityNote: '秋季比满觉陇晚开十余天，人少更符合《迟桂花》意境。可从满觉陇步行前往。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 郁达夫《迟桂花》——翁家山迟桂意境',
  },
  {
    id: 'hz-5', name: '龙井村', desc: '西湖龙井核心产区，乾隆御封"十八棵御茶"',
    duration: '2小时', tags: ['体验', '文化'], timeSlot: '下午',
    location: { lat: 30.2265, lng: 120.1265 }, address: '杭州市西湖区龙井村',
    story: '西湖龙井核心产区，乾隆御封"十八棵御茶"，沿御道攀登可俯瞰阶梯状茶田，观摩炒茶工艺。',
    type: '体验', budgetHint: '免费', goodNow: true, goodNowReason: '下午品茶最惬意', emoji: '🍵',
    originalText: '江南忆，最忆是杭州。山寺月中寻桂子，郡亭枕上看潮头。何日更重游。',
    originalSource: '📖白居易《忆江南》',
    realityNote: '春季可参与采茶体验，在村民家观摩炒茶工艺，品现沏狮峰龙井。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 白居易"最忆是杭州"——龙井村品茶',
  },
  {
    id: 'hz-6', name: '断桥残雪', desc: '许仙与白娘子"断桥相会"传说地',
    duration: '30分钟', tags: ['文化'], timeSlot: '上午',
    location: { lat: 30.2590, lng: 120.1555 }, address: '杭州市西湖区白堤东端',
    story: '许仙与白娘子"断桥相会"的传说发生地，冬雪后桥面阴阳面分合似断，是西湖最浪漫的符号。',
    type: '景点', budgetHint: '免费', photoSpot: true, emoji: '❄️',
    originalText: '湖边多少游湖者，半在断桥烟雨间。',
    originalSource: '📖范仲淹《春日游湖》',
    realityNote: '从白堤步行可达，建议清晨前往避人群。冬季雪后"残雪"意境最佳。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 许仙白娘子断桥相会——西湖最浪漫符号',
  },
  {
    id: 'hz-7', name: '西湖醋鱼', desc: '杭帮菜头牌，草鱼醋汁酸甜适口',
    duration: '1小时', tags: ['美食'], timeSlot: '中午',
    location: { lat: 30.2500, lng: 120.1500 }, address: '楼外楼（孤山路店）',
    story: '西湖醋鱼是杭帮菜的头牌，楼外楼始创于清道光年间，草鱼醋汁酸甜适口，是来杭州必尝的味道。',
    type: '美食', budgetHint: '人均80-150元', goodNow: true, goodNowReason: '午时品尝最佳', emoji: '🐟',
    originalText: '未能抛得杭州去，一半勾留是此湖。',
    originalSource: '📖白居易《春题湖上》',
    realityNote: '楼外楼孤山路店最正宗，推荐西湖醋鱼+龙井虾仁+定胜糕组合。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 杭帮菜文化——西湖醋鱼与楼外楼',
  },
  {
    id: 'hz-8', name: '九溪烟树', desc: '九条溪流汇成的天然氧吧，杭州人私藏徒步胜地',
    duration: '2小时', tags: ['自然', '体验'], timeSlot: '下午',
    location: { lat: 30.2120, lng: 120.1210 }, address: '杭州市西湖区九溪路',
    story: '九条溪流汇成的天然氧吧，溪水潺潺茶园叠翠，雨后云雾缭绕，是杭州人私藏的治愈系徒步胜地。',
    type: '景点', budgetHint: '免费', goodNow: true, goodNowReason: '雨后云雾最美', photoSpot: true, emoji: '🌲',
    originalText: '黑云翻墨未遮山，白雨跳珠乱入船。卷地风来忽吹散，望湖楼下水如天。',
    originalSource: '📖苏轼《六月二十七日望湖楼醉书》',
    realityNote: '雨后云雾缭绕最出片，徒步约1.5-2小时，适合下午悠闲漫步。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 苏轼"黑云翻墨未遮山"——九溪烟树雨后意境',
  },
]

// ============================================================
//  北京 — 📖老舍·史铁生
// ============================================================
const beijingSpots: Spot[] = [
  {
    id: 'bj-1', name: '老舍纪念馆（丹柿小院）', desc: '老舍居所，两棵手植柿树，《茶馆》诞生于此',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 39.9150, lng: 116.4115 }, address: '北京市东城区灯市口西街丰富胡同19号',
    story: '老舍1950-1966年居所，院内两棵1953年手植柿树秋季挂果，《茶馆》《龙须沟》《正红旗下》等24部作品诞生于此。',
    type: '景点', budgetHint: '免费（需预约）', goodNow: true, goodNowReason: '上午人少可静心感受', photoSpot: true, emoji: '🏡',
    originalText: '最爱和平的纯中国人啊，你们在想象中也能看到北平之秋是什么样子吧？',
    originalSource: '📖老舍《四世同堂》',
    realityNote: '需在微信公众号预约，每日8:00放票。秋季柿子挂果时最美，可盖"四世同堂"纪念章。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 老舍故居——丹柿小院，《茶馆》诞生地',
  },
  {
    id: 'bj-2', name: '地坛公园', desc: '史铁生《我与地坛》的文学圣殿',
    duration: '2小时', tags: ['文化', '自然'], timeSlot: '上午',
    location: { lat: 39.9510, lng: 116.4190 }, address: '北京市东城区安定门外大街',
    story: '明清帝王祭地之坛，因史铁生《我与地坛》从古老祭坛升华为文学圣殿，西门银杏大道是他"常坐的那棵柏树"旁的长椅。',
    type: '景点', budgetHint: '2元', goodNow: true, goodNowReason: '秋季银杏大道最美', photoSpot: true, emoji: '🍂',
    originalText: '死是一件不必急于求成的事，死是一个必然会降临的节日。',
    originalSource: '📖史铁生《我与地坛》',
    realityNote: '门票仅2元，西门银杏大道是史铁生同款机位，秋季金黄如画。喂鸽子，读《我与地坛》。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 史铁生《我与地坛》——地坛公园文学圣殿',
  },
  {
    id: 'bj-3', name: '老舍茶馆', desc: '京味文化地标，从两分钱大碗茶起家',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '晚上',
    location: { lat: 39.8990, lng: 116.3975 }, address: '北京市西城区前门西大街3号楼',
    story: '1988年创建的京味文化地标，集六大老北京茶馆形式于一体，从两分钱大碗茶摊起家，接待过80国190多位元首政要。',
    type: '体验', budgetHint: '演出票60-380元/大碗茶2分钱', emoji: '🍵',
    originalText: '大清国不一定好啊，可是到了民国，我挨了饿。',
    originalSource: '📖老舍《茶馆》（常四爷台词）',
    realityNote: '演出需提前购票，推荐选含曲艺节目的场次。大碗茶2分钱是公益项目，值得一尝。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 老舍《茶馆》——老舍茶馆京味体验',
  },
  {
    id: 'bj-4', name: '小杨家胡同', desc: '老舍出生地，《四世同堂》"祁家"原型',
    duration: '45分钟', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 39.9380, lng: 116.3720 }, address: '北京市西城区新街口南大街小杨家胡同',
    story: '老舍出生地，《四世同堂》中"祁家"原型，胡同形如葫芦，"进了葫芦脖子，看见了墙根堆着的垃圾，你才敢放胆往里面走"。',
    type: '景点', budgetHint: '免费', emoji: '🏘️',
    originalText: '说不定，这个地方在当初或者真是个羊圈，因为它不像一般的北平的胡同那样直直的，或略微有一两个弯儿，而是颇像一个葫芦。',
    originalSource: '📖老舍《四世同堂》',
    realityNote: '居民区，参观请安静勿扰民。胡同形如葫芦，从"葫芦嘴"走进去别有洞天。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 老舍《四世同堂》——小杨家胡同"祁家"原型',
  },
  {
    id: 'bj-5', name: '北京鲁迅博物馆', desc: '"老虎尾巴"书房，诞生了《野草》和《彷徨》',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 39.9230, lng: 116.3580 }, address: '北京市西城区阜成门内大街宫门口二条19号',
    story: '鲁迅在北京的故居"老虎尾巴"，不足十平米的小屋诞生了《野草》和《彷徨》，馆藏手稿与珍贵文物。',
    type: '景点', budgetHint: '免费', emoji: '📚',
    originalText: '在我的后园，可以看见墙外有两株树，一株是枣树，还有一株也是枣树。',
    originalSource: '📖鲁迅《秋夜》',
    realityNote: '周二至周日9:00-16:00开放，周一闭馆。免费参观，"老虎尾巴"书房和两株枣树仍在。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 鲁迅《秋夜》——"老虎尾巴"书房与两株枣树',
  },
  {
    id: 'bj-6', name: '白塔寺', desc: '元大都唯一完整遗存，《四世同堂》背景地标',
    duration: '1小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 39.9225, lng: 116.3590 }, address: '北京市西城区阜成门内大街171号',
    story: '元大都唯一完整遗存，老舍等作家笔下的"北京符号"，《四世同堂》以其为背景，红墙白塔映胡同。',
    type: '景点', budgetHint: '20元', photoSpot: true, emoji: '🏯',
    originalText: '阳光一射到城楼上，一切的东西仿佛都有了精神。',
    originalSource: '📖老舍《四世同堂》（德胜门描写）',
    realityNote: '白塔旁有露台咖啡馆，红墙白塔与灰瓦胡同同框，是北京最文艺的拍照点之一。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 老舍《四世同堂》——白塔寺红墙白塔',
  },
  {
    id: 'bj-7', name: '炸酱面', desc: '老舍情有独钟的家常饭，"锅挑"不过水',
    duration: '1小时', tags: ['美食'], timeSlot: '中午',
    location: { lat: 39.9200, lng: 116.4000 }, address: '方砖厂69号炸酱面/海碗居',
    story: '炸酱面是老北京的家常饭，老舍情有独钟。正宗"锅挑"面条不过水，配上六必居黄酱炸的肉酱，再来几样面码儿，就是最地道的北京味。',
    type: '美食', budgetHint: '人均30-50元', goodNow: true, goodNowReason: '午餐必吃', emoji: '🍜',
    originalText: '中秋前后是北平最美丽的时候',
    originalSource: '📖老舍《四世同堂》',
    realityNote: '方砖厂69号炸酱面口碑好，海碗居也是老字号。配豆汁儿焦圈才完整。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 老舍笔下北平家常——炸酱面与豆汁儿',
  },
  {
    id: 'bj-8', name: '鼓楼/钟楼', desc: '百年钟鼓楼，晨钟暮鼓与胡同交织',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 39.9415, lng: 116.3905 }, address: '北京市东城区钟鼓楼',
    story: '百年钟鼓楼藏着京味文学记忆，晨钟暮鼓与胡同交织，是感受北京文学底蕴的地标。',
    type: '景点', budgetHint: '联票20元', photoSpot: true, emoji: '🔔',
    originalText: '中秋前后是北平最美丽的时候',
    originalSource: '📖老舍《四世同堂》',
    realityNote: '登楼可俯瞰胡同全景，推荐下午前往，夕阳中的钟鼓楼与胡同最动人。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 老舍笔下"北平之秋"——钟鼓楼与胡同',
  },
]

// ============================================================
//  成都 — 📖巴金·杜甫
// ============================================================
const chengduSpots: Spot[] = [
  {
    id: 'cd-1', name: '杜甫草堂', desc: '诗圣流寓成都近四年，创作240余首千古名篇',
    duration: '2小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 30.6595, lng: 104.0350 }, address: '四川省成都市青羊区青华路37号',
    story: '杜甫流寓成都近四年的故居，创作240余首千古名篇，《茅屋为秋风所破歌》《春夜喜雨》皆诞生于此，中国文学史上的"圣地"。',
    type: '景点', budgetHint: '50元/学生半价25元', goodNow: true, goodNowReason: '9:00前或16:00后人少', photoSpot: true, emoji: '🏡',
    originalText: '安得广厦千万间，大庇天下寒士俱欢颜，风雨不动安如山！',
    originalSource: '📖杜甫《茅屋为秋风所破歌》',
    realityNote: '9:00前或16:00后入园人少体验更佳。60岁以上中国内地居民免费。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 杜甫《茅屋为秋风所破歌》——杜甫草堂文学圣地',
  },
  {
    id: 'cd-2', name: '巴金故居（慧园）', desc: '以《家》为蓝本建造的川西园林，还原高家大院',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 30.6575, lng: 104.0410 }, address: '成都市青羊区百花潭公园内',
    story: '以巴金小说《家》为蓝本建造的川西园林，还原了高家大院格局，是读懂《家》《春》《秋》的实体入口。',
    type: '景点', budgetHint: '百花潭公园免费', emoji: '🏡',
    originalText: '我是青年，我又不是畸形的人，我不能在这种虚伪的制度下生活。',
    originalSource: '📖巴金《家》（觉慧台词）',
    realityNote: '原正通顺街故居已不存，百花潭公园慧园为依据《家》还原的园林，需明确标注。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 巴金《家》——慧园还原高家大院格局',
  },
  {
    id: 'cd-3', name: '宽窄巷子', desc: '清朝"少城"遗存，"最成都"的代言地',
    duration: '2小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 30.6695, lng: 104.0555 }, address: '四川省成都市青羊区宽巷子27号',
    story: '清朝"少城"遗存，由宽巷子/窄巷子/井巷子组成，盖碗茶+掏耳朵+川剧变脸，"最成都"的代言地。',
    type: '体验', budgetHint: '免费', goodNow: true, goodNowReason: '傍晚灯笼亮起最美', photoSpot: true, emoji: '🏘️',
    originalText: '生活并不是一个悲剧。它是一个"搏斗"。',
    originalSource: '📖巴金《家》序言',
    realityNote: '建议下午+晚上：白天看建筑喝茶，傍晚灯笼亮起逛夜巷。美食去奎星楼街更地道。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 巴金《家》——宽窄巷子"最成都"生活',
  },
  {
    id: 'cd-4', name: '武侯祠', desc: '全国唯一君臣合祀祠庙，杜甫曾写《蜀相》',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 30.6430, lng: 104.0480 }, address: '四川省成都市武侯区武侯祠大街231号',
    story: '全国唯一君臣合祀祠庙，三国文化圣地，杜甫曾写"丞相祠堂何处寻，锦官城外柏森森"。',
    type: '景点', budgetHint: '50元', emoji: '⛩️',
    originalText: '丞相祠堂何处寻，锦官城外柏森森。',
    originalSource: '📖杜甫《蜀相》',
    realityNote: '与锦里古街相邻，可安排连游。8:00-20:00开放，建议上午前往。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 杜甫《蜀相》——武侯祠三国文化圣地',
  },
  {
    id: 'cd-5', name: '浣花溪公园', desc: '诗歌主题公园，杜甫草堂旁"迟日江山丽"',
    duration: '1.5小时', tags: ['自然', '文化'], timeSlot: '下午',
    location: { lat: 30.6560, lng: 104.0380 }, address: '四川省成都市青羊区青华路9号',
    story: '杜甫草堂旁的诗歌主题公园，沿溪步道刻有历代诗词，"迟日江山丽，春风花草香"的意境在此复活。',
    type: '景点', budgetHint: '免费', goodNow: true, goodNowReason: '下午散步最惬意', emoji: '🌿',
    originalText: '迟日江山丽，春风花草香。泥融飞燕子，沙暖睡鸳鸯。',
    originalSource: '📖杜甫《绝句二首》',
    realityNote: '与杜甫草堂联游最佳，沿溪步道读诗词刻石，感受诗圣意境。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 杜甫"迟日江山丽"——浣花溪诗歌步道',
  },
  {
    id: 'cd-6', name: '人民公园（鹤鸣茶社）', desc: '百年盖碗茶灵魂，竹椅茉莉花茶采耳',
    duration: '1.5小时', tags: ['体验', '文化'], timeSlot: '下午',
    location: { lat: 30.6615, lng: 104.0580 }, address: '四川省成都市青羊区少城路12号',
    story: '百年鹤鸣茶社是成都盖碗茶的灵魂所在，竹椅+茉莉花茶+采耳，巴金笔下成都悠闲生活的活态呈现。',
    type: '体验', budgetHint: '采耳30-60元', goodNow: true, goodNowReason: '下午茶最巴适', photoSpot: true, emoji: '🍵',
    originalText: '春天过去了。但是在这个古城里，人们并没有忘记春天。',
    originalSource: '📖巴金《春》',
    realityNote: '竹椅+茉莉花茶+采耳，成都最正宗的慢生活。采耳30-60元，建议下午前往。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 巴金《春》——鹤鸣茶社成都慢生活',
  },
  {
    id: 'cd-7', name: '陈麻婆豆腐', desc: '百年老字号，麻辣鲜香烫的成都名片',
    duration: '1小时', tags: ['美食'], timeSlot: '中午',
    location: { lat: 30.6580, lng: 104.0360 }, address: '青华路店（草堂旁）',
    story: '陈麻婆豆腐是成都百年老字号，麻辣鲜香烫，是来成都必尝的味道。青华路店就在杜甫草堂旁。',
    type: '美食', budgetHint: '人均50-80元', goodNow: true, goodNowReason: '午餐必吃', emoji: '🫕',
    originalText: '晓看红湿处，花重锦官城。',
    originalSource: '📖杜甫《春夜喜雨》',
    realityNote: '青华路店（草堂旁）最正宗，推荐麻婆豆腐+龙抄手+甜水面组合。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 成都美食文化——陈麻婆豆腐百年老字号',
  },
  {
    id: 'cd-8', name: '锦里古街', desc: '西蜀最古老商业街，夜灯笼亮起时最美',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '晚上',
    location: { lat: 30.6425, lng: 104.0475 }, address: '四川省成都市武侯区武侯祠大街231号旁',
    story: '西蜀历史上最古老的商业街之一，现为三国文化与成都小吃集散地，夜灯笼亮起时最美。',
    type: '体验', budgetHint: '免费', goodNow: true, goodNowReason: '夜晚灯笼亮起最美', photoSpot: true, emoji: '🏮',
    originalText: '晓看红湿处，花重锦官城。',
    originalSource: '📖杜甫《春夜喜雨》',
    realityNote: '与武侯祠相邻，建议傍晚前往，灯笼亮起后逛夜巷吃小吃。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 杜甫"花重锦官城"——锦里古街夜色',
  },
]

// ============================================================
//  西安 — 📖唐诗·贾平凹
// ============================================================
const xianSpots: Spot[] = [
  {
    id: 'xa-1', name: '西安城墙', desc: '中国现存最完整古代城垣，黄昏骑行看日落',
    duration: '2.5小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 34.2525, lng: 108.9470 }, address: '西安市碑林区南大街（永宁门）',
    story: '中国现存规模最大、保存最完整的古代城垣，周长13.74公里，黄昏骑行看日落于城楼，是西安独有的浪漫。',
    type: '体验', budgetHint: '54元+自行车45元/3小时', goodNow: true, goodNowReason: '黄昏骑行看日落最美', photoSpot: true, emoji: '🏰',
    originalText: '长安一片月，万户捣衣声。',
    originalSource: '📖李白《子夜吴歌·秋歌》',
    realityNote: '推荐傍晚16:00后登城，避开暴晒看日落。租自行车45元/3小时，环城13.7公里。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 李白"长安一片月，万户捣衣声"——西安城墙',
  },
  {
    id: 'xa-2', name: '大雁塔（大慈恩寺）', desc: '玄奘译经之地，盛唐文化精神图腾',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 34.2185, lng: 108.9645 }, address: '西安市雁塔区慈恩路1号',
    story: '玄奘译经之地，盛唐文化的精神图腾，北广场音乐喷泉为亚洲最大。',
    type: '景点', budgetHint: '大慈恩寺40元+登塔25元', emoji: '🗼',
    originalText: '高阁逼星辰，登临近九天。',
    originalSource: '📖岑参《与高适薛据同登慈恩寺浮图》',
    realityNote: '大慈恩寺40元+登塔25元，北广场音乐喷泉12:00/16:00/19:00/21:00四场。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 岑参"高阁逼星辰"——大雁塔盛唐图腾',
  },
  {
    id: 'xa-3', name: '大唐不夜城', desc: '盛唐风貌步行街，灯光亮起时梦回长安',
    duration: '2小时', tags: ['体验', '文化'], timeSlot: '晚上',
    location: { lat: 34.2180, lng: 108.9685 }, address: '西安市雁塔区慈恩路46号',
    story: '盛唐风貌步行街，不倒翁小姐姐/石头人等真人表演火爆全网，灯光亮起时梦回长安。',
    type: '体验', budgetHint: '免费', goodNow: true, goodNowReason: '7点后灯光亮起最壮观', photoSpot: true, emoji: '🏮',
    originalText: '九天阊阖开宫殿，万国衣冠拜冕旒。',
    originalSource: '📖王维《和贾舍人早朝大明宫之作》',
    realityNote: '7点后灯光亮起，不倒翁小姐姐/石头人真人互动。建议从大雁塔北广场开始步行。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 王维"九天阊阖开宫殿"——大唐不夜城盛唐风貌',
  },
  {
    id: 'xa-4', name: '陕西历史博物馆', desc: '"古都明珠，华夏宝库"，一眼千年',
    duration: '2.5小时', tags: ['文化', '体验'], timeSlot: '上午',
    location: { lat: 34.2270, lng: 108.9585 }, address: '西安市雁塔区小寨东路91号',
    story: '"古都明珠，华夏宝库"，馆藏37万件文物，何家村遗宝、兽首玛瑙杯、唐三彩，一眼千年。',
    type: '景点', budgetHint: '基础馆免费/珍宝馆30元/壁画馆270元', emoji: '🏛️',
    originalText: '三月三日天气新，长安水边多丽人。',
    originalSource: '📖杜甫《丽人行》',
    realityNote: '免费票必须提前3-7天在公众号抢，节假日秒空。珍宝馆30元值得看。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 杜甫"三月三日天气新"——陕西历史博物馆',
  },
  {
    id: 'xa-5', name: '碑林博物馆', desc: '中国最大石刻艺术宝库，颜柳书法圣物汇聚',
    duration: '1.5小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 34.2565, lng: 108.9460 }, address: '西安市碑林区三学街15号',
    story: '中国最大的石刻艺术宝库，颜真卿《多宝塔碑》、柳公权《玄秘塔碑》等书法圣物汇聚，是唐诗的物质载体。',
    type: '景点', budgetHint: '85元', emoji: '🖋️',
    originalText: '劝君更尽一杯酒，西出阳关无故人。',
    originalSource: '📖王维《送元二使安西》（碑林藏碑刻）',
    realityNote: '85元门票，书法爱好者必访。颜柳真迹碑刻在此，是唐诗的物质载体。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 王维"劝君更尽一杯酒"——碑林书法圣物',
  },
  {
    id: 'xa-6', name: '华清宫', desc: '唐玄宗与杨贵妃温泉宫殿，《长恨歌》实景地',
    duration: '2小时', tags: ['文化', '体验'], timeSlot: '下午',
    location: { lat: 34.3580, lng: 109.2145 }, address: '西安市临潼区华清路38号',
    story: '唐玄宗与杨贵妃的温泉宫殿，白居易"春寒赐浴华清池"的实景地，《长恨歌》实景演出是西安最震撼的夜间体验。',
    type: '景点', budgetHint: '120元/长恨歌演出248元起', photoSpot: true, emoji: '♨️',
    originalText: '春寒赐浴华清池，温泉水滑洗凝脂。',
    originalSource: '📖白居易《长恨歌》',
    realityNote: '华清宫120元，《长恨歌》实景演出248元起，是西安最震撼的夜间演出。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 白居易"春寒赐浴华清池"——华清宫长恨歌',
  },
  {
    id: 'xa-7', name: '羊肉泡馍', desc: '掰馍浸汤，西安头牌美食',
    duration: '1小时', tags: ['美食'], timeSlot: '中午',
    location: { lat: 34.2600, lng: 108.9400 }, address: '老孙家/同盛祥',
    story: '羊肉泡馍是西安的头牌美食，亲手掰馍浸入浓郁羊肉汤，是来西安必体验的仪式感。老孙家、同盛祥是百年老字号。',
    type: '美食', budgetHint: '人均35-60元', goodNow: true, goodNowReason: '午餐必吃', emoji: '🍲',
    originalText: '春风得意马蹄疾，一日看尽长安花。',
    originalSource: '📖孟郊《登科后》',
    realityNote: '老孙家/同盛祥为百年老店。掰馍要细，汤才入味。配冰峰+肉夹馍=三秦套餐。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 西安美食文化——羊肉泡馍与三秦套餐',
  },
  {
    id: 'xa-8', name: '贾平凹文化艺术馆', desc: '展示贾平凹书画创作与文学作品',
    duration: '1小时', tags: ['文化'], timeSlot: '下午',
    location: { lat: 34.3695, lng: 109.2150 }, address: '西安市临潼区芷阳三路9号',
    story: '以文学艺术和旅游公共交流为主题，展示贾平凹书画创作与文学作品，建筑风格与先生朴实蓄敛性格互为表里。',
    type: '景点', budgetHint: '20元', emoji: '🎨',
    originalText: '寻君千行泪，含恨归故山',
    originalSource: '📖贾平凹《废都》',
    realityNote: '位于临潼区，可与华清宫安排同日游览。10:00-18:00开放。',
    culturalTag: '📖书籍', culturalTagDetail: '📖 贾平凹《废都》——贾平凹文化艺术馆',
  },
]

// ============================================================
//  组装完整攻略
// ============================================================
const now = new Date().toISOString()

export const nationalCityGuides: Record<string, Guide> = {
  fenghuang: {
    id: 'fenghuang',
    title: '边城凤凰',
    subtitle: '跟着沈从文，走进茶峒的水墨世界',
    city: '凤凰',
    province: '湖南',
    days: 2,
    interests: ['文化', '体验', '自然'],
    budget: '舒适',
    dayPlans: buildDayPlans(fenghuangSpots, 2),
    dialect: [
      { dialect: '么么（苗语）', meaning: '谢谢', scenario: '进苗寨喝拦门酒时必说，否则连灌三碗' },
      { dialect: '阿妹/阿哥', meaning: '对年轻男女的称呼', scenario: '别叫"小姐"，要叫"阿妹"' },
      { dialect: '毕兹卡', meaning: '本地人（土家语自称）', scenario: '土家族自我介绍时使用' },
      { dialect: '赶场', meaning: '赶集', scenario: '农历逢二、七的腊尔山赶集' },
      { dialect: '高山流水', meaning: '苗族敬酒方式', scenario: '阿姐层层叠碗倒酒，不停喝' },
      { dialect: '拦门酒', meaning: '苗寨迎客礼', scenario: '进寨必喝，端碗站门口拦路' },
    ],
    localExperiences: [
      { name: '沱江晨雾观赏', desc: '清晨6:00-7:30，薄雾贴水面，吊脚楼若隐若现', type: '体验', schedule: '清晨6:00-7:30' },
      { name: '苗服旅拍', desc: '淡季妆造+服装80-150元/套', type: '体验', schedule: '全天' },
      { name: '蜡染扎染非遗体验', desc: '虹桥附近工坊，30元/人，作品可带走', type: '手艺', schedule: '全天' },
      { name: '《边城》实景演出', desc: 'VIP区580元/A区260元/B区220元，沉浸式再现翠翠故事', type: '民俗', schedule: '晚间' },
      { name: '苗寨长桌宴', desc: '老家寨/竹山村，打糍粑、学苗绣', type: '民俗', schedule: '需预约' },
    ],
    createdAt: now,
    tips: [
      '古城自2023年起取消大门票，全天免费进入，核心九景联票128元',
      '最佳季节：4-6月、9-10月；11-3月淡季性价比较高',
      '高铁直达"凤凰古城站"，转磁浮/接驳车7元约10-15分钟到古城',
      '跳岩石面湿滑，拍照务必站稳扶好',
      '夜景19:00准时亮灯',
      '警惕低价团和路边"免费体验"的隐形消费',
    ],
    entryType: '书籍',
    relatedBook: '《边城》',
    relatedAuthor: '沈从文',
    routeIntro: '「由四川过湖南去，靠东有一条官路。这官路将近湘西边境到了一个地方名为"茶峒"的小山城时，有一小溪，溪边有座白色小塔，塔下住了一户单独的人家。」沈从文《边城》开篇，写的就是这片土地。泛舟沱江、走过跳岩、登上虹桥——凤凰的每一处风景，都是《边城》的注脚。',
  },
  shanghai: {
    id: 'shanghai',
    title: '繁花上海',
    subtitle: '跟着《繁花》与张爱玲，走进上海的旧时光',
    city: '上海',
    province: '上海',
    days: 2,
    interests: ['文化', '美食', '体验'],
    budget: '舒适',
    dayPlans: buildDayPlans(shanghaiSpots, 2),
    dialect: [
      { dialect: '不响', meaning: '不说话/沉默', scenario: '《繁花》核心词，心中有数但不言语' },
      { dialect: '阿拉', meaning: '我们/咱们', scenario: '最具上海特色的代词' },
      { dialect: '爷叔', meaning: '叔叔/长辈尊称', scenario: '阿宝对贵人的尊称，亦师亦父' },
      { dialect: '白相', meaning: '玩耍/娱乐', scenario: '"弄堂里白相"即弄堂里玩耍' },
      { dialect: '小赤佬', meaning: '小鬼头（亲昵）', scenario: '看似贬义实则长辈对晚辈的宠溺' },
      { dialect: '噱头', meaning: '花招/卖点', scenario: '做生意"三头"之一' },
      { dialect: '派头', meaning: '排场/气派', scenario: '做生意"三头"之二' },
      { dialect: '拆烂污', meaning: '敷衍/不负责任', scenario: '形容做事不认真' },
    ],
    localExperiences: [
      { name: '繁花同款Citywalk', desc: '东正教堂→复兴公园→国泰电影院→花园饭店→兰心大戏院→进贤路→黄河路→和平饭店→外滩27号', type: '体验', schedule: '全天约4-5小时' },
      { name: '上海影视乐园繁花实景', desc: '1:1复刻黄河路/进贤路，门票80元', type: '体验', schedule: '8:30-16:30' },
      { name: '弄堂早餐', desc: '咸豆浆配生煎包，九江路观景位看国际饭店晨光', type: '体验', schedule: '清晨' },
      { name: '鲁迅虹口散步', desc: '鲁迅故居→甜爱路→山阴路', type: '体验', schedule: '上午' },
    ],
    createdAt: now,
    tips: [
      '《繁花》黄河路实景在车墩影视乐园，非真实现场；真正的黄河路在市区免费参观',
      '张爱玲故居（常德公寓）不对外开放，仅可外观拍照，请勿扰民',
      '鲁迅纪念馆正在闭馆修缮中（截至2026年6月），故居与鲁迅墓正常开放',
      '推荐沪语版《繁花》观看，方言韵味是灵魂',
      '国际饭店蝴蝶酥常年排队，建议早上8点前往',
    ],
    entryType: '目的地',
    relatedBook: '《繁花》',
    relatedAuthor: '金宇澄 / 张爱玲 / 鲁迅',
    routeIntro: '「做生意要先学会两个字，不响。」金宇澄《繁花》写尽了上海人的精明与深情。从和平饭店的百年传奇到黄河路的繁华烟火，从张爱玲的爱丁顿公寓到鲁迅的山阴路——上海的故事，藏在弄堂的每一扇窗后。',
  },
  hangzhou: {
    id: 'hangzhou',
    title: '诗画杭州',
    subtitle: '跟着白居易、苏轼与郁达夫，漫步西湖',
    city: '杭州',
    province: '浙江',
    days: 2,
    interests: ['文化', '自然', '体验'],
    budget: '舒适',
    dayPlans: buildDayPlans(hangzhouSpots, 2),
    dialect: [
      { dialect: '弄堂', meaning: '巷子/胡同', scenario: '杭州老城区街巷' },
      { dialect: '落雨', meaning: '下雨', scenario: '"今天落雨了"' },
      { dialect: '吃茶', meaning: '喝茶', scenario: '杭州茶文化日常用语' },
      { dialect: '蛮好', meaning: '很好', scenario: '最常用的评价词' },
      { dialect: '搞七捻三', meaning: '胡搞/瞎忙', scenario: '形容做事不着调' },
      { dialect: '木牢牢', meaning: '很多/非常多', scenario: '"人木牢牢"即人很多' },
      { dialect: '勿搭界', meaning: '没关系/不相干', scenario: '表示事不关己' },
    ],
    localExperiences: [
      { name: '龙井村采茶制茶', desc: '春季可参与采茶体验，观摩炒茶工艺', type: '体验', schedule: '春季' },
      { name: '灵隐寺旁禅茶体验', desc: '法云安缦区域漫步天竺古道，茶园旁茶寮品茗参禅', type: '体验', schedule: '全天' },
      { name: '茅家埠秘境泛舟', desc: '西湖"秘境中的秘境"，古树古道亭台楼阁', type: '体验', schedule: '全天' },
      { name: '秋季翁家山寻迟桂花', desc: '追随郁达夫脚步感受"迟"与"慢"', type: '时令', schedule: '9-10月' },
      { name: '宝石山日落俯瞰', desc: '登保俶塔旁观景台，看夕阳染金西湖', type: '体验', schedule: '傍晚' },
    ],
    createdAt: now,
    tips: [
      '西湖景区免费开放，部分景点（灵隐寺、雷峰塔等）单独售票',
      '春秋两季最佳：3-5月龙井新绿、9-11月桂花飘香',
      '环湖骑行推荐：租自行车沿苏堤白堤骑行，省力又惬意',
      '灵隐寺需先购飞来峰门票（45元）再购灵隐寺门票（30元），合计75元',
      '秋季赏桂必去满觉陇，但翁家山更符合《迟桂花》意境且人少',
    ],
    entryType: '目的地',
    relatedBook: '《钱塘湖春行》',
    relatedAuthor: '白居易 / 苏轼 / 郁达夫',
    routeIntro: '「未能抛得杭州去，一半勾留是此湖。」白居易、苏轼、郁达夫，千年文人在西湖边写下了最美的诗句。白堤上的绿杨、苏堤上的春晓、灵隐寺的禅意、翁家山的迟桂——杭州的诗情，都写在湖山之间。',
  },
  beijing: {
    id: 'beijing',
    title: '北平之秋',
    subtitle: '跟着老舍与史铁生，读一座城的精神史',
    city: '北京',
    province: '北京',
    days: 2,
    interests: ['文化', '体验', '美食'],
    budget: '舒适',
    dayPlans: buildDayPlans(beijingSpots, 2),
    dialect: [
      { dialect: '甭', meaning: '不用/别', scenario: '"甭客气"' },
      { dialect: '局气', meaning: '仗义/大方', scenario: '夸人靠谱讲规矩' },
      { dialect: '门儿清', meaning: '非常清楚/门道熟', scenario: '"这事儿我门儿清"' },
      { dialect: '发小儿', meaning: '从小一起长大的朋友', scenario: '北京最亲的朋友称呼' },
      { dialect: '范儿', meaning: '气质/派头', scenario: '"有范儿"即有气质' },
      { dialect: '老炮儿', meaning: '老江湖/有资历的人', scenario: '胡同里德高望重者' },
      { dialect: '门脸儿', meaning: '店面/门面', scenario: '"到了德胜门门脸儿"' },
    ],
    localExperiences: [
      { name: '胡同文学散步', desc: '老舍故居→五四大街→景山万春亭，秋天柿子树红果压枝', type: '体验', schedule: '秋季最佳' },
      { name: '地坛银杏大道', desc: '西门银杏大道坐长椅（史铁生同款机位），喂鸽子', type: '体验', schedule: '10-11月' },
      { name: '老舍茶馆听戏喝茶', desc: '看京味演出+品大碗茶，体验六大老北京传统茶馆形式', type: '民俗', schedule: '14:00-21:00' },
      { name: '白塔寺胡同咖啡', desc: '红墙白塔与灰瓦胡同同框', type: '体验', schedule: '下午' },
    ],
    createdAt: now,
    tips: [
      '老舍纪念馆需在微信公众号预约，每日8:00放票',
      '秋季最佳：柿子挂果、银杏金黄，与老舍笔下的"北平之秋"完美契合',
      '地坛公园门票仅2元，西门银杏大道是史铁生同款机位',
      '小杨家胡同为居民区，参观请安静勿扰民',
      '老舍茶馆演出需提前购票，推荐选含曲艺节目的场次',
    ],
    entryType: '目的地',
    relatedBook: '《四世同堂》',
    relatedAuthor: '老舍 / 史铁生',
    routeIntro: '「北平之秋便是天堂。」老舍用最朴素的话，写出了北京最美的季节。从丹柿小院的柿子树到地坛银杏大道的长椅，从小杨家胡同的葫芦形到白塔寺的红墙——这座城市的文学记忆，藏在每一条胡同深处。',
  },
  chengdu: {
    id: 'chengdu',
    title: '诗圣故里',
    subtitle: '跟着杜甫与巴金，感受成都的慢与诗',
    city: '成都',
    province: '四川',
    days: 2,
    interests: ['文化', '美食', '体验'],
    budget: '舒适',
    dayPlans: buildDayPlans(chengduSpots, 2),
    dialect: [
      { dialect: '巴适', meaning: '舒服/好', scenario: '"这茶巴适得很"' },
      { dialect: '安逸', meaning: '舒适/享受', scenario: '成都人最高评价' },
      { dialect: '要得', meaning: '好的/可以', scenario: '表示同意' },
      { dialect: '摆龙门阵', meaning: '聊天/闲谈', scenario: '成都茶馆核心活动' },
      { dialect: '雄起', meaning: '加油/鼓劲', scenario: '最具川人精神的口号' },
      { dialect: '耍', meaning: '玩', scenario: '"走，出去耍"' },
      { dialect: '瓜娃子', meaning: '傻瓜（带亲昵）', scenario: '嗔怪语气常用' },
    ],
    localExperiences: [
      { name: '盖碗茶+掏耳朵', desc: '人民公园鹤鸣茶社，竹椅+茉莉花茶+采耳30-60元', type: '体验', schedule: '全天' },
      { name: '草堂诗会', desc: '每日10:00/15:00诗史堂有志愿者朗诵杜甫诗歌', type: '民俗', schedule: '10:00/15:00' },
      { name: '川剧变脸', desc: '宽窄巷子内川剧馆，近距离感受变脸绝技', type: '民俗', schedule: '每日' },
      { name: '浣花溪诗歌步道', desc: '沿溪散步，读历代诗词刻石，杜甫草堂联游', type: '体验', schedule: '全天' },
    ],
    createdAt: now,
    tips: [
      '杜甫草堂9:00前或16:00后入园人少体验更佳',
      '宽窄巷子建议下午+晚上：白天看建筑喝茶，傍晚灯笼亮起逛夜巷',
      '美食去奎星楼街（本地人最爱）比宽窄巷子更好吃更便宜',
      '杜甫草堂门票50元，60岁以上中国内地居民免费',
      '7-8月暑期延时开放至18:30',
    ],
    entryType: '目的地',
    relatedBook: '《茅屋为秋风所破歌》',
    relatedAuthor: '杜甫 / 巴金',
    routeIntro: '「安得广厦千万间，大庇天下寒士俱欢颜。」杜甫在成都草堂写下的千古名句，至今回荡在浣花溪畔。从杜甫草堂到巴金慧园，从鹤鸣茶社的盖碗茶到宽窄巷子的川剧变脸——成都的慢，是诗人的慢；成都的诗，是生活本身的诗意。',
  },
  xian: {
    id: 'xian',
    title: '盛唐长安',
    subtitle: '跟着唐诗与贾平凹，梦回千年帝都',
    city: '西安',
    province: '陕西',
    days: 2,
    interests: ['文化', '体验', '美食'],
    budget: '舒适',
    dayPlans: buildDayPlans(xianSpots, 2),
    dialect: [
      { dialect: '嫽得太', meaning: '非常好/美得很', scenario: '最高评价' },
      { dialect: '噷（hén）', meaning: '吝啬', scenario: '"这人噷得很"' },
      { dialect: '扎势', meaning: '摆谱/装样子', scenario: '形容人做作' },
      { dialect: '谝（piǎn）', meaning: '聊天/闲谈', scenario: '"咱俩谝一谝"' },
      { dialect: '么麻达', meaning: '没问题', scenario: '最常用的肯定回答' },
      { dialect: '额', meaning: '我', scenario: '关中话自称' },
      { dialect: '克里马擦', meaning: '快点/麻利', scenario: '催促时使用' },
      { dialect: '碎怂', meaning: '小子/小鬼', scenario: '对小孩的称呼' },
    ],
    localExperiences: [
      { name: '城墙骑行', desc: '租自行车黄昏时分从永宁门出发，13.7公里看日落', type: '体验', schedule: '16:00后' },
      { name: '长恨歌实景演出', desc: '华清宫夜间演出，票价248元起，西安最震撼的文化演艺', type: '民俗', schedule: '晚间' },
      { name: '永兴坊非遗美食', desc: '比回民街清净，biangbiang面/肉夹馍/冰峰三秦套餐', type: '体验', schedule: '全天' },
      { name: '大唐不夜城夜游', desc: '7点后灯光亮起，不倒翁小姐姐/石头人真人互动', type: '体验', schedule: '19:00后' },
    ],
    createdAt: now,
    tips: [
      '陕西历史博物馆免费票必须提前3-7天在公众号抢，节假日秒空',
      '城墙骑行推荐傍晚16:00后登城，避开暴晒，看日落最美',
      '洒金桥比回民街更本地更便宜，是西安人私藏美食街',
      '大雁塔北广场音乐喷泉：12:00/16:00/19:00/21:00四场',
      '棣花古镇距西安市区约160km/2.5小时车程，适合安排一整天',
    ],
    entryType: '目的地',
    relatedBook: '《长恨歌》',
    relatedAuthor: '白居易 / 李白 / 贾平凹',
    routeIntro: '「春风得意马蹄疾，一日看尽长安花。」孟郊的这句诗，写尽了长安的气象。从城墙骑行到大雁塔，从大唐不夜城的灯火到华清宫的长恨歌——西安的每一块砖石，都刻着唐诗的韵律。',
  },
}
